spring:
  profiles:
    active: @profileActive@

  redis:
    host: 192.168.245.133
    port: 6379
    password: 123456
    timeout: 3000ms


server:
  port: 8080
  servlet:
    context-path: /api


file:
  upload-path: D:\temp\upload\